import type { DocId } from './types';

/* Corpus de busca/RAG: texto puro por seção, extraído dos 4 PDFs.
   Gerado a partir de docs/extracted. Editável para refinar a recuperação. */

export type Chunk = { docId: DocId; sectionId: string; title: string; text: string };

export const CHUNKS: Chunk[] = [
  {
    "docId": "atendimento",
    "sectionId": "principios",
    "title": "Princípios éticos do atendimento",
    "text": "quatro pilares indissociáveis: Confidencialidade (Segredo Profissional): O sigilo das informações do paciente é protegido pelo Código de Ética Médica (CFM), pelo Código de Defesa do Consumidor e, especialmente, pela Lei Geral de Proteção de Dados (LGPD – Lei nº 13.709/2018). Dados de saúde são considerados sensíveis e exigem cuidado redobrado. Na recepção, isso significa evitar a exposição inadvertida de diagnósticos, históricos ou informações pessoais em conversas ao alcance de outros pacientes. Não-discriminação: Todo paciente tem o direito de ser tratado com igualdade, independentemente de raça, cor, etnia, religião, procedência, condição socioeconômica, orientação sexual, identidade de gênero ou qualquer outra característica pessoal. A recepção deve acolher a todos com o mesmo respeito e cordialidade. Empatia: A capacidade de se colocar no lugar do outro é a base do cuidado humanizado. O paciente que chega à clínica pode estar ansioso, com dor, medo ou insegurança. A escuta ativa e a comunicação acolhedora reduzem o estresse e aumentam a adesão ao tratamento. Dignidade do Paciente: Cada pessoa é um ser único, com história, valores e necessidades próprias. O atendimento deve preservar sua autonomia, respeitar suas decisões e tratá-la com cortesia, sem julgamentos. A dignidade se expressa no tom de voz, no respeito ao tempo de espera e na privacidade durante as interações. Este Manual consolida as diretrizes éticas e operacionais para a recepção, oferecendo um roteiro prático de atendimento (script) integrado a notas explicativas que fundamentam cada etapa. O documento deve ser utilizado como POP (Procedimento Operacional Padrão) e está alinhado às melhores práticas de gestão em saúde."
  },
  {
    "docId": "atendimento",
    "sectionId": "jornada",
    "title": "A jornada do atendimento em 5 etapas",
    "text": "2. Script de Atendimento com Notas Explicativas As seções a seguir apresentam o diálogo modelo entre recepcionista (R) e paciente (P), seguidas de notas explicativas que detalham a fundamentação ética e a aplicação prática de cada etapa. 2.1 Saudação Inicial e Acolhimento Diálogo modelo: R: \"Bom dia / Boa tarde / Boa noite! Seja bem-vindo(a) à [Nome da Clínica]. Meu nome é [Nome do Recepcionista]. Como posso ajudá-lo(a) hoje?\" P: \"Olá, tenho consulta marcada com o Dr. Silva às 10h.\" R: \"Excelente, vou providenciar o seu atendimento. Enquanto isso, por favor, sinta-se à vontade para se acomodar na sala de espera. Oferecemos água e café à disposição.\" Nota explicativa – Humanização: A saudação deve ser feita com contato visual, sorriso genuíno e tom de voz calmo. Evitar iniciar a conversa com perguntas fechadas como \"Tem convênio?\" ou \"Já veio aqui?\" – priorizar o acolhimento. O uso do nome do paciente (quando conhecido) é um diferencial de humanização, mas deve ser feito com naturalidade, sem forçar intimidade. Oferecer conforto (água, café, lugar sentado) transmite cuidado desde o primeiro instante. 2.2 Identificação e Confirmação Segura de Dados Diálogo modelo: R: \"Para darmos continuidade, você poderia me mostrar um documento oficial com foto e o cartão do convênio, por favor? Obrigado(a).\" R: (Após receber os documentos, em tom discreto) \"Vou apenas confirmar seus dados para sua segurança. Seu nome completo é [Nome Completo]? A data de nascimento é [DD/MM/AAAA]? O telefone para contato ainda é [Número]? E o médico de hoje será o Dr. [Nome], correto?\" P: \"Sim, está tudo certo.\" R: \"Perfeito, obrigado(a). Seus dados estão atualizados em nosso sistema.\" Nota explicativa – LGPD e Privacidade: A confirmação de dados deve ser feita em tom de voz baixo para evitar que outro…"
  },
  {
    "docId": "atendimento",
    "sectionId": "scripts",
    "title": "Scripts modelo",
    "text": "2.1 Saudação Inicial e Acolhimento Diálogo modelo: R: \"Bom dia / Boa tarde / Boa noite! Seja bem-vindo(a) à [Nome da Clínica]. Meu nome é [Nome do Recepcionista]. Como posso ajudá-lo(a) hoje?\" P: \"Olá, tenho consulta marcada com o Dr. Silva às 10h.\" R: \"Excelente, vou providenciar o seu atendimento. Enquanto isso, por favor, sinta-se à vontade para se acomodar na sala de espera. Oferecemos água e café à disposição.\" Nota explicativa – Humanização: A saudação deve ser feita com contato visual, sorriso genuíno e tom de voz calmo. Evitar iniciar a conversa com perguntas fechadas como \"Tem convênio?\" ou \"Já veio aqui?\" – priorizar o acolhimento. O uso do nome do paciente (quando conhecido) é um diferencial de humanização, mas deve ser feito com naturalidade, sem forçar intimidade. Oferecer conforto (água, café, lugar sentado) transmite cuidado desde o primeiro instante. 2.2 Identificação e Confirmação Segura de Dados Diálogo modelo: R: \"Para darmos continuidade, você poderia me mostrar um documento oficial com foto e o cartão do convênio, por favor? Obrigado(a).\" R: (Após receber os documentos, em tom discreto) \"Vou apenas confirmar seus dados para sua segurança. Seu nome completo é [Nome Completo]? A data de nascimento é [DD/MM/AAAA]? O telefone para contato ainda é [Número]? E o médico de hoje será o Dr. [Nome], correto?\" P: \"Sim, está tudo certo.\" R: \"Perfeito, obrigado(a). Seus dados estão atualizados em nosso sistema.\" Nota explicativa – LGPD e Privacidade: A confirmação de dados deve ser feita em tom de voz baixo para evitar que outros pacientes ouçam informações sensíveis. Sempre que possível, utilizar o visor do computador para que o próprio paciente veja seus dados, evitando repetir em voz alta itens como CPF ou endereço completo. A coleta e o armazenamento de dado…"
  },
  {
    "docId": "atendimento",
    "sectionId": "situacoes-delicadas",
    "title": "Protocolos de situações delicadas",
    "text": "3. Protocolos Éticos para Situações Delicadas 3.1 Atraso do Paciente Situação: Paciente chega atrasado para a consulta agendada (ex.: 20 minutos após o horário). Conduta ética: R: \"Compreendo que imprevistos acontecem. Como o seu horário era às [Hora], o sistema já alocou a vaga para outro paciente. Vou verificar com a equipe se é possível encaixá-lo(a) hoje. O tempo de espera será de aproximadamente [X] minutos. Se preferir, podemos reagendar para outro dia sem custos.\" Fundamentação: O equilíbrio entre respeito à agenda do médico e acolhimento ao paciente é crucial. O recepcionista não deve repreender o paciente, mas sim explicar a situação de forma objetiva e oferecer alternativas. A decisão de encaixar cabe ao médico e à equipe de enfermagem. Nunca deixar o paciente sem resposta – informar o prazo de espera estimado e a possibilidade de reagendamento evita frustração. 3.2 Ausência de Documentos Obrigatórios Situação: Paciente esqueceu o documento de identidade ou o cartão do convênio. Conduta ética: R: \"Entendo que isso pode acontecer. Para realizar o atendimento pelo convênio, a operadora exige a apresentação do documento de identificação. Você possui o aplicativo do [Nome do Convênio] ou o documento digital (RG/CNH digital) no celular? Se sim, podemos validar por ali.\" R: (Se não tiver acesso digital) \"Infelizmente, sem o documento físico ou digital, não conseguiremos registrar o atendimento pelo convênio. Mas você pode optar por realizar a consulta como particular e depois solicitar o reembolso à operadora. O valor da consulta particular hoje é R$ [Valor]. Gostaria de prosseguir assim?\" R: (Se o paciente não puder pagar) \"Entendo perfeitamente. Vamos remarcar sua consulta para uma data próxima, e você lembra de trazer os documentos. Não se preocupe, não haverá cu…"
  },
  {
    "docId": "atendimento",
    "sectionId": "codigo-conduta",
    "title": "Código de conduta",
    "text": "5. Código de Conduta Rápido para a Recepção Este resumo operacional deve estar visível em cada posto de trabalho. Item Conduta Esperada Postura Corporal Sempre sentado(a) de forma ereta, braços apoiados na bancada, mãos visíveis. Evitar cruzar os braços (postura defensiva) ou se recostar na cadeira. Manter contato visual durante toda a interação. Tom de Voz Calmo, pausado, em volume moderado. Evitar gritar para chamar pacientes ou falar ao telefone em tom alto. Usar entonação amigável, especialmente ao confirmar dados. Confidencialidade Visual de Telas e Papéis Manter o monitor do computador posicionado de forma que pacientes em espera não vejam a tela. Bloquear a tela (Windows+L) sempre que se ausentar do posto. Documentos com dados pessoais devem ser guardados em pastas ou gavetas. Nunca deixar fichas, guias ou recibos expostos sobre o balcão. Atendimento Telefônico Atender no máximo até o terceiro toque. Identificar a clínica e a si mesmo(a). Evitar atender telefone enquanto atende um paciente presencial – pedir licença e informar que retornará a ligação. Nunca deixar o paciente presencial esperando por mais de 30 segundos sem explicação. Postura Digital Não utilizar celular pessoal ou acessar redes sociais durante o expediente. O sistema da clínica deve ser o único foco de atenção. Em caso de necessidade urgente, comunicar a supervisão. Atendimento a Pessoas com Deficiência Falar diretamente com a pessoa, não com o acompanhante (a menos que solicitado). Oferecer ajuda, mas não impor. Para pessoas surdas, usar linguagem escrita ou aplicativos de tradução. Para pessoas cegas, descrever o ambiente e orientar com clareza. Atualização e Treinamento Participar de todos os treinamentos de atendimento humanizado e LGPD. Ler e reler este Manual periodicamente. Reportar à sup…"
  },
  {
    "docId": "crc",
    "sectionId": "voz",
    "title": "A voz como primeiro contato",
    "text": "1.1 A Voz como Primeiro Contato Acolhedor A Central de Relacionamento com o Cliente (CRC) constitui a primeira porta de entrada do paciente na clínica. Diferentemente do atendimento presencial, onde a linguagem corporal, o sorriso e o ambiente físico contribuem para o acolhimento, no contato telefônico ou digital a voz assume o papel exclusivo de transmitir segurança, empatia e profissionalismo. Cada saudação inicial, cada pausa e cada entonação carregam o poder de reduzir a ansiedade do paciente ou, ao contrário, de acentuá-la. Por essa razão, a equipe da CRC deve ser treinada para modular o tom de voz, evitando monotonia ou pressa, e para demonstrar presença plena durante a chamada, sem interrupções ou ruídos de fundo que denotem desatenção. O paciente que liga para agendar uma consulta frequentemente já vivencia algum grau de desconforto — seja físico, emocional ou administrativo — e cabe ao operador da CRC transformar essa experiência inicial em um momento de confiança e cuidado. A literatura em humanização da saúde demonstra que a percepção de acolhimento pelo paciente está diretamente correlacionada à adesão ao tratamento e à redução do absenteísmo. Um paciente que se sente ouvido e respeitado na primeira ligação tende a comparecer à consulta com maior comprometimento e a recomendar a clínica a terceiros. Portanto, o investimento em comunicação empática na CRC não é apenas uma questão ética, mas também estratégica para a sustentabilidade do negócio. Cada interação deve ser encarada como uma oportunidade única de construir vínculo, independentemente da duração da chamada."
  },
  {
    "docId": "crc",
    "sectionId": "pilares",
    "title": "Pilares éticos do agendamento",
    "text": "1.2 Confidencialidade e Privacidade na Coleta de Dados Sensíveis (LGPD) A coleta de dados pessoais e de saúde durante o agendamento envolve informações sensíveis que exigem rigorosa proteção. A Lei Geral de Proteção de Dados (LGPD — Lei nº 13.709/2018) estabelece que dados relativos à saúde são considerados dados pessoais sensíveis , cujo tratamento exige consentimento específico e finalidade determinada. No contexto da CRC, isso significa que o operador deve coletar apenas as informações estritamente necessárias para a marcação e elegibilidade do convênio, jamais extrapolando para perguntas invasivas ou desnecessárias. Ao confirmar dados como CPF, número da carteirinha ou histórico de consultas anteriores, o operador deve fazê-lo em tom discreto, evitando repetir informações sensíveis em voz alta em ambiente compartilhado. Adicionalmente, o sistema de registro de agendamentos deve contar com controles de acesso baseados em perfis, garantindo que apenas operadores autorizados visualizem os prontuários e que qualquer consulta seja auditável. O paciente tem o direito de saber como seus dados serão armazenados e por quanto tempo. O operador da CRC deve estar preparado para responder a perguntas sobre proteção de dados de forma clara e transparente, e, em caso de dúvidas mais complexas, direcionar o paciente ao Encarregado de Proteção de Dados (DPO) da clínica. A confidencialidade não é uma opção — é um dever ético e legal que sustenta a confiança na relação entre paciente e instituição. 1.3 Equidade e Não-Discriminação no Acesso às Agendas O princípio da equidade no agendamento significa que todos os pacientes devem ter acesso igualitário às vagas disponíveis, independentemente de idade, gênero, origem étnica, condição socioeconômica, tipo de convênio ou qualquer outra car…"
  },
  {
    "docId": "crc",
    "sectionId": "chamada-perfeita",
    "title": "O roadmap da chamada perfeita",
    "text": "2.1 Saudação Inicial e Acolhimento Nota ao operador: A saudação deve ser feita com o nome completo do operador, em tom pausado e caloroso. Evite cumprimentos genéricos como \"alô\" sem identificação. O paciente precisa saber imediatamente com quem está falando e em qual instituição. Operador: \"Bom dia! Você está falando com [Nome do Operador], da Central de Agendamento da [Nome da Clínica]. É um prazer atender você. Como posso ajudá-lo hoje?\" Após a saudação, aguarde a resposta do paciente sem interromper. Demonstre escuta ativa através de pequenos sons de confirmação (\"hum-hum\", \"entendi\") ou pausas respeitosas. Caso o paciente esteja chorando ou muito angustiado, acolha emocionalmente antes de qualquer procedimento burocrático: \"Sinto muito que você esteja passando por isso. Estou aqui para ajudar.\" 2.2 Triagem e Entendimento da Necessidade Nota ao operador: Antes de ofertar horários, é essencial entender o motivo do contato. Pergunte abertamente e escute sem pressa. A escuta ativa reduz retrabalho e evita agendamentos incorretos. Operador: \"Para que eu possa direcionar seu atendimento da melhor forma, você poderia me contar qual é o principal motivo da sua ligação? É para agendar uma consulta, marcar um exame, ou tirar alguma dúvida?\" Se o paciente relatar sintomas que indiquem urgência (como dor intensa, falta de ar, sangramento, febre alta), o operador deve acionar o Protocolo de Direcionamento para Pronto-Atendimento (descrito na seção 3.3). Não tente fazer diagnóstico — seu papel é encaminhar com segurança e rapidez. Se a necessidade for eletiva, prossiga com a coleta de dados. Caso o paciente já tenha preferência por especialista: Operador: \"Perfeito! O(a) senhor(a) já tem algum médico ou especialidade de preferência? Ou gostaria de conhecer as opções disponíveis …"
  },
  {
    "docId": "crc",
    "sectionId": "protocolos",
    "title": "Protocolos para situações complexas",
    "text": "3.1 Falta de Vagas na Agenda para a Especialidade Desejada A indisponibilidade de horários é uma das situações mais frequentes e potencialmente geradoras de frustração no paciente. O operador deve abordar o tema com transparência e oferecer alternativas antes que o paciente sinta que seu problema foi ignorado. A primeira ação é validar a necessidade: \"Entendo que você precisa ser atendido(a) o mais breve possível. Infelizmente, não temos horários disponíveis para essa especialidade nas próximas duas semanas.\" Em seguida, apresente opções reais, jamais prometa o que não pode cumprir. Opções éticas a serem oferecidas: 1. Fila de espera: \"Posso inseri-lo(a) na nossa fila de espera para essa especialidade. Assim que surgir um horário vago por cancelamento, entraremos em contato. O senhor(a) autoriza?\" 2. Especialista alternativo: \"O Dr. Carlos atende a mesma especialidade e tem disponibilidade na quinta-feira. Gostaria de agendar com ele?\" 3. Unidade próxima: \"Temos outra unidade na Zona Sul com vagas para amanhã. O deslocamento é viável para você?\" 4. Telemedicina: Se disponível, ofereça a opção de consulta online como alternativa temporária. Jamais minta ou invente prazos irreais para \"acalmar\" o paciente. Se a fila de espera é longa, seja honesto: \"A média de espera é de 30 dias.\" O paciente tem o direito de decidir com informações reais. Registre no sistema a recusa ou aceitação de cada alternativa para rastreabilidade e compliance ético. 3.2 Paciente Irritado com a Demora na Marcação ou Instabilidade no Sistema A irritação do paciente geralmente não é dirigida ao operador pessoalmente, mas sim ao sistema, à burocracia ou à demora. O primeiro passo é acolher a emoção sem se defender ou justificar. Técnicas de desescalada comprovadas incluem: nomear o sentimento do pacie…"
  },
  {
    "docId": "crc",
    "sectionId": "regra-5-minutos",
    "title": "A Regra dos 5 minutos",
    "text": "em até 5 minutos após a chamada, garantindo que o paciente receba a informação ainda fresca na memória. Esse processo reduz drasticamente o absenteísmo e gera confiança na marca."
  },
  {
    "docId": "crc",
    "sectionId": "conduta",
    "title": "Código de conduta do operador",
    "text": "5. Código de Conduta para Operadores de CRC Dimensão Diretriz O que evitar Postura Vocal Manter tom de voz médio, pausado e com entonação variada. Sorrir antes de falar — o sorriso é audível. Monotonia, pressa na dicção, tom robotizado, falar com objetos na boca (chicletes, alimentos). Escuta Ativa Não interromper o paciente. Usar frases confirmatórias (\"Compreendo\", \"Entendo\"). Repetir informações-chave do paciente para verificar compreensão. Interromper para \"ganhar tempo\", julgar a queixa do paciente, completar frases. Registro de Prontuários Registrar exatamente o que foi combinado: horário, profissional, orientações, recados do paciente. Usar linguagem objetiva e neutra. Inserir opiniões pessoais (\"paciente parece estressado\"), abreviações não padronizadas, campos obrigatórios em branco. Proteção de Dados Confirmar identidade do paciente antes de fornecer qualquer informação. Não deixar telas abertas com dados visíveis a terceiros. Bloquear o sistema ao levantar. Compartilhar dados por telefone com terceiros sem autorização, anotar senhas em post-its. Ergonomia e Foco Manter postura sentada correta, tela na altura dos olhos, pausas de 5 minutos a cada hora para evitar fadiga vocal e mental. Atender chamadas enquanto digita sem pausa, realizar múltiplas tarefas, permanecer imóvel por longos períodos. Empatia e Respeito Tratar todos os pacientes com o mesmo padrão de cortesia, independentemente do convênio ou do tom do paciente. Diferenciar tratamento por classe social, idade ou tom de voz do paciente. Revidar grosseria. \"A qualidade do atendimento na Central de Relacionamento não é medida pela velocidade da chamada, mas pela segurança e pelo acolhimento que o paciente sente ao desligar o telefone.\""
  },
  {
    "docId": "marketing",
    "sectionId": "pilares",
    "title": "Os 3 pilares de conteúdo 40/40/20",
    "text": "2. Pilares Estratégicos de Vídeo para Clínicas Para que o conteúdo em vídeo gere resultados previsíveis e mensuráveis, é fundamental estruturá-lo em três pilares complementares. Cada pilar atende a um estágio diferente da jornada do paciente, do primeiro contato à decisão de agendar uma consulta. Nota: Proporção recomendada de distribuição: 40% Conexão, 40% Autoridade, 20% Conversão. Essa divisão equilibra engajamento orgânico, construção de confiança e geração de leads. 2.1 Vídeos de Conexão (Bastidores e Humanização) Os vídeos de conexão humanizam a clínica e aproximam o paciente da realidade do atendimento. Eles mostram que por trás da marca existem pessoas que se importam. Exemplos práticos: ● Preparação diária: gravação rápida da abertura da clínica, recepção sendo organizada, cafeteira ligada. ● Processos de higiene: esterilização de instrumentos, limpeza das salas, cuidados com a biossegurança (essencial para odontologia e estética). ● Valores da equipe: depoimentos curtos de profissionais sobre o que mais amam em suas áreas. 2.2 Vídeos de Autoridade (Educação e Esclarecimento) Esses vídeos posicionam os profissionais da clínica como referências em suas especialidades. Devem ser informativos, baseados em evidências e responder diretamente às dúvidas mais comuns dos pacientes. Exemplos: ● Mitos e verdades: “Colocar aparelho nos dentes dói mesmo?” (odontologia); “É verdade que quem tem problema na coluna não pode fazer musculação?” (fisioterapia). ● Explicação de sintomas: vídeos de 30 a 60 segundos sobre sinais de alerta (dor de cabeça frequente, manchas na pele, cansaço excessivo). ● Tecnologia disponível: demonstração de equipamentos modernos (laser, scanner intraoral, ultrassom) e seus benefícios para o paciente. 2.3 Vídeos de Conversão (Experiência e Facilidad…"
  },
  {
    "docId": "marketing",
    "sectionId": "calendario",
    "title": "Calendário editorial",
    "text": "3. Calendário Semanal de Stories Os Stories são o canal ideal para manter um relacionamento próximo e diário com os seguidores. A seguir, um modelo de roteiro semanal que pode ser adaptado conforme a agenda da clínica e a disponibilidade dos profissionais. Dia Tema Descrição Segunda Começo de semana com energia Vídeo rápido da abertura da clínica, recepção pronta e equipe se preparando. Use um texto motivacional e mostre que a clínica está a postos para receber os pacientes. Terça Caixa de perguntas Abra uma caixa de perguntas nos stories com um tema específico (ex.: “Dúvidas sobre implantes dentários” ou “Exercícios para melhorar a postura”). Depois, responda às 3–5 perguntas mais relevantes em vídeos de até 1 minuto. Quarta Bastidores e equipe Apresente um profissional diferente a cada semana. Mostre um pouco da rotina dele dentro da clínica e um detalhe pessoal (hobby, livro, paixão). Humanização gera vínculo. Quinta Mito vs. Verdade Grave um vídeo curto (máx. 30s) desmentindo um boato comum relacionado à saúde bucal, postural, estética ou nutricional. Inclua o profissional especialista no tema. Sexta Dica de bem-estar + CTA sutil Público está mais relaxado para o fim de semana. Dê uma dica leve (alongamento, hidratação, cuidado com a pele) e finalize com um reminder: “Prevenir é o melhor remédio. Agende sua avaliação pelo link da bio”. Sáb/Dom Conexão leve Conteúdo de estilo de vida saudável: vídeos dos profissionais praticando esportes, cozinhando algo saudável, lendo. Mostre que a equipe vive o que prega. “A consistência nos Stories é mais importante que a produção sofisticada. Um vídeo de celular com boa iluminação e áudio limpo vale mais que um vídeo profissional postado uma vez por mês.” 4. Calendário Mensal Coringa para o Feed (4 Semanas) O feed deve ser trata…"
  },
  {
    "docId": "marketing",
    "sectionId": "anatomia",
    "title": "Anatomia do vídeo eficaz",
    "text": "Roteirização em 3 etapas (Gancho + Conteúdo + CTA): Todo vídeo deve começar com uma frase que pare o scroll (ex.: “Você sabia que ranger os dentes pode causar dores de cabeça?”), entregar a informação principal em 20–40 segundos e encerrar com uma chamada sutil (ex.: “Compartilhe com quem precisa saber disso”)."
  },
  {
    "docId": "marketing",
    "sectionId": "formulas",
    "title": "3 fórmulas de roteiro",
    "text": "Fórmulas Práticas de Storytelling para o Dia a Dia da Clínica Para facilitar a produção de conteúdo ágil, utilize estas três estruturas de roteiro validadas para gravação rápida no celular: 1. A Fórmula do \"Inimigo Comum\": o O Gancho: Identifique um hábito nocivo ou um mito (ex: \"A procrastinação da saúde\"). o O Desenvolvimento: Explique por que esse 'inimigo' é perigoso (ex: \"Deixar aquele check-up para depois pode transformar um problema simples em algo complexo\"). o A Solução: Como a clínica ajuda a vencer esse inimigo (ex: \"Nosso protocolo de avaliação rápida foi desenhado para quem não tem tempo a perder\"). 2. A Fórmula da \"Descoberta\": o O Gancho: Comece pelo impacto (ex: \"Como um tratamento de 30 minutos mudou a rotina de sono da Maria\"). o O Desenvolvimento: Narre o momento da 'virada' (ex: \"Ela não sabia que a dor na mandíbula era a causa da sua insônia crônica até fazermos o diagnóstico X\"). o A Lição: O aprendizado que o público pode levar (ex: \"Muitas vezes, a solução para o seu cansaço está onde você menos imagina\"). 3. A Fórmula do \"Bastidor com Propósito\": o O Gancho: Mostre um detalhe técnico (ex: \"Por que usamos este tipo específico de luz no consultório?\"). o O Desenvolvimento: Explique o benefício invisível para o paciente (ex: \"Não é apenas estética; essa tecnologia permite identificar lesões que o olho humano não veria, garantindo sua segurança\"). o O Fechamento: Reforce o valor da clínica (ex: \"Cada detalhe aqui tem um único objetivo: o seu melhor cuidado\")."
  },
  {
    "docId": "marketing",
    "sectionId": "storytelling",
    "title": "Storytelling ético",
    "text": "6. Storytelling na Saúde e Bem-Estar O storytelling na área da saúde não deve ser confundido com entretenimento superficial, mas sim compreendido como uma ferramenta poderosa de humanização e educação. Narrativas bem estruturadas permitem que o paciente se projete na jornada de cuidado, transformando o medo do desconhecido em confiança no processo terapêutico. 6.1 A Importância da Narrativa para a Conexão Dados técnicos e descrições de procedimentos ativam áreas lógicas do cérebro, mas as histórias ativam áreas ligadas à empatia e à memória. Ao compartilhar uma trajetória de superação, a clínica deixa de ser apenas um prestador de serviços para se tornar uma aliada na busca por qualidade de vida. 6.2 Estruturando Narrativas Reais e Éticas Para manter a autoridade técnica e a conformidade ética, a estrutura narrativa deve focar na **Jornada do Paciente**, seguindo três atos fundamentais: ● O Desafio (A Dor): Descreva o sintoma, a limitação funcional ou a insegurança estética de forma respeitosa (ex: \"A dificuldade de mastigar que impedia o convívio social\"). ● A Travessia (O Cuidado): Apresente o papel da clínica e do profissional como guias técnicos que oferecem acolhimento, tecnologia e um plano personalizado. ● A Transformação (O Bem-Estar): Foque no ganho de vida, na retomada da autoestima ou no fim da dor crônica. Nota: Evite promessas de resultados idênticos para todos; foque na melhora da percepção de saúde do indivíduo. 6.3 Exemplos Práticos de Roteiros por Especialidade Abaixo, sugestões de abordagens narrativas para diferentes áreas: ● Odontologia (Quebrando o medo): \"Muitos pacientes adiam o sonho do sorriso novo por traumas antigos com o 'barulhinho do motor'. Hoje, mostramos como a sedação consciente e o atendimento em tempo estendido mudaram a percepção de …"
  },
  {
    "docId": "marketing",
    "sectionId": "producao",
    "title": "Checklist de produção",
    "text": "5. Boas Práticas de Produção Gestores de clínicas têm uma rotina intensa. Por isso, as dicas a seguir são pensadas para otimizar tempo sem comprometer a qualidade do conteúdo. 1. Roteirização em 3 etapas (Gancho + Conteúdo + CTA): Todo vídeo deve começar com uma frase que pare o scroll (ex.: “Você sabia que ranger os dentes pode causar dores de cabeça?”), entregar a informação principal em 20–40 segundos e encerrar com uma chamada sutil (ex.: “Compartilhe com quem precisa saber disso”). 2. Iluminação básica: Use luz natural (janela à frente) ou um ring light de LED com temperatura ajustável (5.000K a 5.500K é o ideal). Evite luz mista (natural + fluorescente) para não criar sombras estranhas. 3. Áudio limpo: Invista em um microfone de lapela sem fio (modelos a partir de R$ 150). Em clínicas, o eco de corredores e equipamentos pode arruinar o som do celular. 4. Legendas automáticas: Use o CapCut ou InShot para gerar legendas sincronizadas. Mais de 70% do público assiste vídeos sem som. Legendas dinâmicas (palavra destacada) aumentam a retenção. 5. Gravação em lote: Reserve 1 hora por mês para gravar todos os vídeos do feed com cada profissional. Use um tripé e um local fixo com boa iluminação. Edite e programe tudo de uma vez. 6. Mantenha a ética: Nunca prometa resultados, não use imagens de antes/depois sem autorização expressa do paciente (e mesmo assim, com cuidado), não faça sensacionalismo. O foco deve ser sempre informar e acolher."
  },
  {
    "docId": "marketing",
    "sectionId": "funil",
    "title": "O funil 5Ns para tráfego pago",
    "text": "7. Módulo Prático: O Funil de Vídeos 5Ns para Tráfego Pago Para que o investimento em anúncios (tráfego pago) traga resultados consistentes, a clínica deve distribuir seus vídeos de acordo com o nível de consciência do público. O Funil 5Ns organiza essa jornada, permitindo que a verba seja alocada de forma inteligente para atrair, educar e converter pacientes. N1: Inconsciente ● Objetivo: Chamar a atenção de quem ainda não sabe que tem um problema. ● Direção: Mostrar um sintoma visível, cotidiano ou incômodo. ● Abordagem: Vídeo educativo e ilustrativo, sem vender no início. ● Foco: Despertar curiosidade e fazer a pessoa pensar: \"isso acontece comigo\" . N2: Consciente do Problema ● Objetivo: Fazer a pessoa reconhecer o problema e o impacto dele. ● Direção: Focar na dor emocional, na identificação e na qualidade de vida. ● Abordagem: Ilustrar situações reais da rotina, autoestima ou segurança. ● Foco: Mostrar que o problema não deve ser ignorado ou adiado. N3: Consciente da Solução ● Objetivo: Apresentar a solução como caminho para resolver o problema. ● Direção: Conectar a dor com a solução de forma simples e direta. ● Abordagem: Explicar o tratamento, técnica ou procedimento de modo educativo. ● Foco: Mostrar o benefício principal e a transformação possível após o cuidado. N4: Consciente do Produto (A Clínica) ● Objetivo: Mostrar por que esse tratamento ou serviço na sua clínica é a escolha certa. ● Direção: Explicar como funciona o seu atendimento e destacar seus diferenciais. ● Abordagem: Evidenciar a equipe, tecnologia, estrutura, método e autoridade. ● Foco: Gerar confiança e posicionar a clínica como a escolha mais segura. N5: Totalmente Consciente ● Objetivo: Gerar ação direta (conversão). ● Direção: Vídeo curto, direto e focado na facilidade de agendamento. ● Abo…"
  },
  {
    "docId": "pop",
    "sectionId": "ecossistema",
    "title": "Ecossistema de Excelência Clínica",
    "text": "A clínica organiza-se em três camadas: Linha de Frente (Recepção, CRC, CRC Comercial — acolhimento e conversão), Motor Clínico (TSB, ASB, Enfermagem, Radiologia, Serviços Gerais — precisão e biossegurança) e Centro de Comando (Gerente/Financeiro — previsibilidade e crescimento)."
  },
  {
    "docId": "pop",
    "sectionId": "pops-por-cargo",
    "title": "POPs por cargo",
    "text": "CARGO: Recepcionista 1. Apresentaçã o Pessoal e Ambiente ● Uniforme e Postura: Estar sempre uniformizado(a), com boton/crachá visí vel e aparê ncia pessoal impecá vel. Manter postura acolhedora e profissional ao receber os pacientes. ● Ambiente: Garantir que a recepçã o esteja sempre limpa, organizada e com materiais necessá rios. Verificar periodicamente o conforto do ambiente (temperatura, mú sica ambiente, etc.). Ligar o computador e verificar os emails antes das 09h. Telefone da clí nica ligado e com bateria. 2. Recepção de Pacientes ● Chegada: Cumprimentar o paciente com cordialidade e empatia, identificando-se pelo nome. Confirmar o horário agendado e solicitar documentos necessários (RG, CPF, comprovante de endereço). ● Cadastro: Verificar se o paciente já está registrado no sistema. Para novos pacientes, realizar o cadastro completo, incluindo dados pessoais, contatos e informações relevantes para o atendimento. 3. Controle de Agendamento ● Check-in: Registrar a chegada do paciente no sistema e informar à equipe clí nica. Acompanhar o fluxo de atendimento, garantindo que todos sejam atendidos no horá rio previsto. ● Atrasos: Informar ao paciente, com educaçã o, qualquer atraso na agenda e oferecer uma previsã o de atendimento. ● Ausê ncias: Registrar no sistema caso o paciente nã o compareç a e, se possí vel, reagendar imediatamente. 4. Atendimento Telefô nico e Digital ● Padrã o de Atendimento Telefônico: Atender chamadas com cordialidade, identificando-se com o nome da clí nica e oferecendo ajuda. Registrar recados e repassar à equipe responsá vel. ● Atendimento Digital: Responder mensagens recebidas por WhatsApp, e-mail ou outros canais com rapidez e profissionalismo. Encaminhar dú vidas complexas para o setor responsá vel (ex.: comercial ou financeiro). 5. O"
  }
];
